runtime: nodejs
vm: true

env_variables:
  # --REQUIRED--
  DATABASE_URI: mongodb://<testdb>:<123456>@ds028540.mlab.com:28540/cashci
  APP_ID: <myAppId>
  MASTER_KEY: <myMasterKey>
  # --OPTIONAL--
  # FILE_KEY: <your-file-key>
  # PARSE_MOUNT: /parse
  # CLOUD_CODE_MAIN:  
